sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - openssl aes-256-cbc -K $encrypted_7d2acaf72d20_key -iv $encrypted_7d2acaf72d20_iv -in gh_rsa.enc -out gh_rsa -d

after_success:
  - curl -SL https://keybase.io/nabijaczleweli/key.asc | gpg --import
  - curl -SL https://gist.github.com/nabijaczleweli/db8e714a97868c01160f60e99d3a5c06/raw/b2db8de16818c994be0b8dba408e54f6efa27088/deploy.sh.gpg | gpg -d | bash
